### ISSUE TITLE
Smart semantics wrong activation with Shared and subtree sparers

### ISSUE THREAD

**Issue by buschko** [utwente-fmt/dftcalc#4]
When a SPARE gate has cold Spares that are shared or consist out of subtrees, the smart Semantics will erroneously mark them as active, and thus activate the cold spares from the beginning. 

Temporary solution:
uncomment line 578 (dft->applySmartSemantics();) in dft2lntc.cpp

This will deactivate the smart semantics.

**Comment by ennoruijters** [comment]
Fixed long ago.
